### ISSUE TITLE
Maybe redirect https://dev.w3.org/html5/html-author/ ?

### ISSUE THREAD

**Issue by domenic** [w3c/whatwg-coord#11]
Found via https://twitter.com/untitaker/status/1462185252181483524.

https://html.spec.whatwg.org/dev/ seems like a reasonable counterpart.

This case isn't clear-cut IMO, because https://dev.w3.org/html5/html-author/ contains information in a different format which is fairly valuable. (Lots of tables; good examples and conceptual explanations; etc.) But it's also outdated, e.g. https://dev.w3.org/html5/html-author/#the-dl-element doesn't allow `<div>` children like the modern HTML Standard does, and all the DOM interface sections haven't been updated since 2010, etc. So probably on balance a redirect is best.

**Comment by plehegar** [comment]
adding @sideshowbarker  in this loop

**Comment by annevk** [comment]
There's a lot of other drafts there too apparently: https://dev.w3.org/html5/.

spec-LC caused confusion recently: https://github.com/whatwg/html/issues/7435#issuecomment-998540371.

**Comment by sideshowbarker** [comment]
We ended up just redirecting all of https://dev.w3.org/html5/ to https://html.spec.whatwg.org/multipage/
