### ISSUE TITLE
New WHATWG Living Standard: File System

### ISSUE THREAD

**Issue by foolip** [w3c/whatwg-coord#12]
This is a heads up that in https://github.com/whatwg/sg/issues/176 we are creating a new Living Standard, File System, which will include portions of https://wicg.github.io/file-system-access/. https://github.com/whatwg/fs/pull/1 shows what it will look like and what the attribution looks like. (It's similar to previous cases.)

Note that this is covered in https://www.w3.org/2019/04/WHATWG-W3C-MOU.html#forking:
> Movement or copying text from incubation-track or non-standards track deliverables shall also be acceptable.

**Comment by plehegar** [comment]
For the record, I did not hear any concern from our side.

**Comment by plehegar** [comment]
Unless I hear otherwise, I'll close this issue in a week since we don't need to do further coordination here.
