### ISSUE TITLE
Change WebSockets redirects to https://websockets.spec.whatwg.org/

### ISSUE THREAD

**Issue by domenic** [w3c/whatwg-coord#13]
- https://www.w3.org/TR/websockets/
- https://w3c.github.io/websockets/

would be nice if these went to https://websockets.spec.whatwg.org/ , whereas right now they respectively go to https://html.spec.whatwg.org/multipage/ and https://html.spec.whatwg.org/multipage/web-sockets.html .

**Comment by plehegar** [comment]
done
