### ISSUE TITLE
Moving Page Visibility

### ISSUE THREAD

**Issue by plehegar** [w3c/whatwg-coord#16]
Per https://github.com/w3c/page-visibility/issues/74

- [x] WHATWG integrates the spec in HTML
- [x] [Page Visibility 2](https://www.w3.org/TR/2021/CR-page-visibility-2-20210518/) gets Discontinued
- [x] https://www.w3.org/TR/page-visibility/  redirects
- [ ] W3C endorses a new iteration of HTML as REC and [Page Visibility 1](https://www.w3.org/TR/2013/REC-page-visibility-20131029/) is marked Obsolete (the WG may mark it obsolete before then).

**Comment by sideshowbarker** [comment]
https://www.w3.org/TR/page-visibility/ now redirects to https://html.spec.whatwg.org/multipage/interaction.html#page-visibility
