### ISSUE TITLE
Some old HTML fork subpages don't have obsolence warnings

### ISSUE THREAD

**Issue by domenic** [w3c/whatwg-coord#18]
https://www.w3.org/TR/2017/REC-html52-20171214/

Compare to https://www.w3.org/TR/2017/REC-html51-20171003/ , which properly has a warning redirecting you to https://www.w3.org/TR/html51/ (which redirects).

**Comment by domenic** [comment]
Hmm, actually what's happening here is that only the index pages have the obsoleted banner. If you deep-link into either version, you get no warning that you're looking at outdated content:

- https://www.w3.org/TR/2017/REC-html51-20171003/introduction.html
- https://www.w3.org/TR/2017/REC-html52-20171214/introduction.html

**Comment by plehegar** [comment]
@deniak @@jennyliang220 How easy would it be to propagate the obsolescence to the multi-pages?

**Comment by deniak** [comment]
This should now work better with multipage documents

**Comment by domenic** [comment]
It seems like since I added this comment there's an obsolete banner, so yeah, closing as satisfied!
