### ISSUE TITLE
Moving WebIDL

### ISSUE THREAD

**Issue by plehegar** [w3c/whatwg-coord#3]
- [x] Document is published by WHATWG
- [x] w3.org/TR/WebIDL points to WHATWG/WebIDL
- [x] W3C Web Platform Working Group gets closed
- [x] W3C WebApps charter gets updated to include WebIDL
- [ ] W3C retires WebIDL 1

Q: Shall W3C retire [WebIDL Level 1](https://www.w3.org/TR/2016/REC-WebIDL-1-20161215/) or do we need to wait for W3C to endorse one WHATWG/WebIDL as REC to do so? (reminder: the plan is not endorse as REC unless someone the WG asks to do so)

**Comment by plehegar** [comment]
If we follow the example of CORS, the answer is yes, we should retire WebIDL Level 1, even if we don't have a REC republished.

**Comment by plehegar** [comment]
WebApps charter: https://github.com/w3c/webappswg/issues/49

**Comment by foolip** [comment]
WHATWG workstream creation is in https://github.com/whatwg/sg/pull/167

**Comment by plehegar** [comment]
One more point: W3C should probably supersede WebIDL 1 once the WHATWG stream is up.

**Comment by foolip** [comment]
@annevk and I have coordinated with @heycam today to get https://webidl.spec.whatwg.org/ up and https://heycam.github.io/webidl/ redirecting. I've checked the "Document is published by WHATWG" box in the description to reflect this.

**Comment by plehegar** [comment]
I added https://github.com/whatwg/meta/issues/223

**Comment by plehegar** [comment]
[/TR/WebIDL](http://www.w3.org/TR/webidl) now redirects to WHATWG WebIDL. Note that /TR/WebIDL-1 waits for WebIDL to get retired.

**Comment by plehegar** [comment]
Waiting on https://www.w3.org/Member/wiki/DirectorFOdashboard#Web_Applications_proposed_charter

**Comment by sideshowbarker** [comment]
https://www.w3.org/TR/WebIDL-1/ now redirects to https://webidl.spec.whatwg.org/
