### ISSUE TITLE
Moving Worklets

### ISSUE THREAD

**Issue by plehegar** [w3c/whatwg-coord#5]
- [x] WHATWG integrates the spec in HTML
- [x] WD [Worklets Level 1](https://www.w3.org/TR/2020/WD-worklets-1-20200908/) is retired
- [ ] W3C endorses a new iteration of HTML as REC with Worklets in it

**Comment by plehegar** [comment]
[Worklets](https://html.spec.whatwg.org/multipage/worklets.html#worklets) is in HTML.

**Comment by plehegar** [comment]
Reached out to CSS Chairs. Plan is to do the same as [Microdata](https://www.w3.org/TR/2021/NOTE-microdata-20210128/).

**Comment by plehegar** [comment]
(Worklets scheduled to be retired on July 29)

**Comment by plehegar** [comment]
https://www.w3.org/TR/worklets-1/ is now retired.

**Comment by domenic** [comment]
Hi, great to see that worklets-1 is retired! Thank you for doing that!

Is there any chance that it, and other cases like it (listed under ["Retired Notes (should redirect)"](https://wiki.whatwg.org/wiki/Fork_tracking)), could be redirected or emptied of their content (as was done for the ["Confusion mitigated"](https://wiki.whatwg.org/wiki/Fork_tracking) cases)?

**Comment by plehegar** [comment]
The redirect was done on https://www.w3.org/TR/worklets/ but, right, not on https://www.w3.org/TR/worklets-1/ . we can do that.

emptied their content is certainly a possibility but we do get complains when we do so :( . That's why I added a banner in bottom right to say "Retired document. Do not use.".

**Comment by domenic** [comment]
Well, redirects are even better than emptied content, so if we can do redirects for those cases, that'd be awesome!

**Comment by plehegar** [comment]
Request sent to our webmaster. Should get done within 24 hours or so.

**Comment by plehegar** [comment]
I went through the "Confusion persists with some mitigation" category and fixed stuff on our side.

**Comment by plehegar** [comment]
Btw, not sure where "https://www.w3.org/TR/webmessaging/" comes from but we don't seem to used to have a spec for that.

**Comment by domenic** [comment]
Thanks so much; that's really great!

TR/webmessaging seems to have existed at some point: https://www.w3.org/blog/news/archives/4704 links to https://www.w3.org/TR/2015/REC-webmessaging-20150519/ (which still exists) which itself links to https://www.w3.org/TR/webmessaging/ (which 404s).

**Comment by plehegar** [comment]
webmessaging done

**Comment by plehegar** [comment]
I noticed you [flagged a few redirects](https://wiki.whatwg.org/wiki/Fork_tracking) to be done. I requested those. I'm also in the process of updating our steps to retire/supersede/etc. documents to make sure we don't forget those things and also get somewhat consistent in our approach.

**Comment by plehegar** [comment]
As a side, with the upcoming approval of a DOM snapshot as REC, we're about to deprecate DOM 3 Core, following advise at https://github.com/w3c/transitions/issues/357 . Let me know if other things on the DOM side need attention.

**Comment by sideshowbarker** [comment]
https://www.w3.org/TR/worklets/ and https://www.w3.org/TR/worklets-1/ now both redirect to https://html.spec.whatwg.org/multipage/, so I’m going ahead and closing this.
