### ISSUE TITLE
Moving Preload

### ISSUE THREAD

**Issue by plehegar** [w3c/whatwg-coord#7]
- [x] WHATWG integrates in HTML
- [x] WHATWG published as part of HTML
- [x] W3C retires the CR and do the /TR redirect to /TR/html

**Comment by plehegar** [comment]
[Web Performance June 24 minutes](https://docs.google.com/document/d/1P_Of7nCFf_UkE_Bvz6rFCNcETPZ_IyxQqRcUsx4L6do/edit#heading=h.3b3idaeuca8x)

**Comment by plehegar** [comment]
(note: it seems that the desire to publish a new draft in the webperf died down)

**Comment by plehegar** [comment]
See also https://github.com/w3c/preload/issues/154

@yoavweiss @caribouW3 can web perf republish preload as a discontinued draft?

**Comment by domenic** [comment]
I think https://github.com/w3c/preload/issues/154#issuecomment-1040534051 is still pending; /cc @noamr

**Comment by noamr** [comment]
> I think https://github.com/w3c/preload/issues/154#issuecomment-1040534051 is still pending; /cc @noamr

On it

**Comment by yoavweiss** [comment]
The PR was merged and [Preload](https://w3c.github.io/preload/) is now a Discontinued Draft (with some errors :/)

**Comment by noamr** [comment]
> The PR was merged and [Preload](https://w3c.github.io/preload/) is now a Discontinued Draft (with some errors :/)

Errors fixed.

**Comment by domenic** [comment]
Sorry, I'm a bit confused where the appropriate times for fetching and processing a `<link rel=preload>` live now?

**Comment by noamr** [comment]
> Sorry, I'm a bit confused where the appropriate times for fetching and processing a `<link rel=preload>` live now?

You're right, we've missed transferring that bit. I'll open an HTML issue and tend to it.

**Comment by noamr** [comment]
https://github.com/whatwg/html/issues/7760

**Comment by plehegar** [comment]
The editor's draft of preload should also be retired by the way.
