### ISSUE TITLE
Fetch

### ISSUE THREAD

**Issue by plehegar** [w3c/whatwg-coord#9]
- [ ] HTML charter gets updated to include Fetch
- [x] CORS is retired and /TR/cors point to Fetch (was done as part of MoU 2019)

**Comment by annevk** [comment]
Now that IANA updates can be done through GitHub, I'm attempting to update existing CORS header registrations from provisional to permanent. I figured I'd give this repository a heads up:

* https://github.com/protocol-registries/http-fields/issues/3
* https://github.com/protocol-registries/http-fields/issues/4
* https://github.com/protocol-registries/http-fields/issues/5
* https://github.com/protocol-registries/http-fields/issues/6
* https://github.com/protocol-registries/http-fields/issues/7
* https://github.com/protocol-registries/http-fields/issues/8
* https://github.com/protocol-registries/http-fields/issues/9

**Comment by sideshowbarker** [comment]
Closing this as done per discussion with plh
